"""rai serve — expose a RAI agent via the LangGraph API server.

Generates a temporary graph module + langgraph.json, then spawns
``langgraph dev`` so the agent is accessible through the LangGraph REST API
(and optionally LangSmith Studio) — no hand-written langgraph.json required.

Usage
-----
    rai serve                        # dev mode, port 2024, opens Studio
    rai serve --no-browser           # dev mode, no browser
    rai serve --no-dev               # server mode (no hot reload)
    rai serve --agent pentest --port 8080
    rai serve --host 0.0.0.0 --workers 4
"""

from __future__ import annotations

import json
import os
import tempfile
import textwrap
from pathlib import Path
from typing import Annotated, Optional

import typer

from rai.serve import ServeConfig as _ServeConfig, _spawn_langgraph

# ---------------------------------------------------------------------------
# Server graph template — mirrors what TUI's _start_server_background() does
# ---------------------------------------------------------------------------

_GRAPH_TEMPLATE = textwrap.dedent("""\
    \"\"\"RAI server graph — auto-generated by `rai serve`. Do not edit.\"\"\"
    from __future__ import annotations
    import asyncio, os, sys
    from pathlib import Path

    _src = {src_path!r}
    if _src not in sys.path:
        sys.path.insert(0, _src)

    from rai.engine.factory import create_rai_agent
    from rai.agents.loader import load_subagents_for
    from rai.mcp.loader import resolve_and_load_mcp_tools, load_subagents_mcp_tools_map

    # ── Config from env vars set by `rai serve` ──────────────────────────────
    _model        = os.environ.get("RAI_SERVE_MODEL",        {default_model!r})
    _agent        = os.environ.get("RAI_SERVE_AGENT",        "rai")
    _api_key      = os.environ.get("RAI_SERVE_API_KEY",      "")
    _base_url     = os.environ.get("RAI_SERVE_BASE_URL",     "")
    _target       = os.environ.get("RAI_SERVE_TARGET",       "")
    _rate_limit   = os.environ.get("RAI_SERVE_RATE_LIMIT",   "")
    _cwd_str      = os.environ.get("RAI_SERVE_CWD",          "")
    _cwd          = Path(_cwd_str) if _cwd_str else Path.cwd()
    _hitl         = os.environ.get("RAI_SERVE_HITL",         "0") == "1"

    # ── Load MCP tools (main agent + all subagents) in parallel ──────────────
    async def _load_all_mcp():
        async def _main_mcp():
            try:
                return await resolve_and_load_mcp_tools(cwd=_cwd, agent_name=_agent)
            except Exception:
                return [], None, []

        async def _sub_mcp():
            try:
                defs = load_subagents_for(_agent)
                if not defs:
                    return {{}}, []
                names = [s["name"] for s in defs if s.get("name")]
                return await load_subagents_mcp_tools_map(names)
            except Exception:
                return {{}}, []

        return await asyncio.gather(_main_mcp(), _sub_mcp())


    def _build() -> object:
        (mcp_tools, _, mcp_info), (subagent_tools_map, _) = asyncio.run(_load_all_mcp())

        _graph, _ = create_rai_agent(
            model=_model,
            agent_name=_agent,
            extra_tools=mcp_tools,
            mcp_server_info=mcp_info,
            subagent_tools_map=subagent_tools_map or None,
            api_key=_api_key,
            base_url=_base_url,
            target=_target,
            rate_limit_profile=_rate_limit,
            cwd=_cwd,
            interactive=False,
            auto_approve=not _hitl,
        )
        return _graph


    graph = _build()
""")


def _write_workspace(
    tmp: Path,
    *,
    src_path: str,
    default_model: str,
    env_file: str | None,
) -> Path:
    """Write rai_graph.py + langgraph.json into *tmp* and return config path."""
    (tmp / "rai_graph.py").write_text(
        _GRAPH_TEMPLATE.format(src_path=src_path, default_model=default_model),
        encoding="utf-8",
    )

    config: dict = {
        "dependencies": ["."],
        "graphs": {"agent": "./rai_graph.py:graph"},
    }
    if env_file:
        config["env"] = env_file

    config_path = tmp / "langgraph.json"
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
    return config_path



def _build_env(
    *,
    model: str,
    agent: str,
    api_key: str,
    base_url: str,
    target: str,
    rate_limit: str,
    cwd: str,
    hitl: bool = False,
) -> dict[str, str]:
    env = os.environ.copy()
    env["RAI_SERVE_MODEL"]      = model
    env["RAI_SERVE_AGENT"]      = agent
    env["RAI_SERVE_API_KEY"]    = api_key
    env["RAI_SERVE_BASE_URL"]   = base_url
    env["RAI_SERVE_TARGET"]     = target
    env["RAI_SERVE_RATE_LIMIT"] = rate_limit
    env["RAI_SERVE_CWD"]        = cwd
    env["RAI_SERVE_HITL"]       = "1" if hitl else "0"
    env["LANGGRAPH_AUTH_TYPE"]  = "noop"
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    for key in ("LANGGRAPH_AUTH", "LANGGRAPH_CLOUD_LICENSE_KEY",
                "LANGSMITH_CONTROL_PLANE_API_KEY", "LANGSMITH_TENANT_ID"):
        env.pop(key, None)
    return env


# ---------------------------------------------------------------------------
# Typer command
# ---------------------------------------------------------------------------


def serve(
    agent:      Annotated[str,  typer.Option("--agent",    "-a",  help="Agent name to serve")] = "rai",
    model:      Annotated[str,  typer.Option("--model",    "-m",  help="Model override (default: RAI_MODEL env or built-in)")] = "",
    port:       Annotated[int,  typer.Option("--port",     "-p",  help="Port to bind")] = 2024,
    host:       Annotated[str,  typer.Option("--host",            help="Host to bind")] = "127.0.0.1",
    dev:        Annotated[bool, typer.Option("--dev/--no-dev",    help="Hot reload on (--dev, default) or off (--no-dev)")] = True,
    browser:    Annotated[bool, typer.Option("--browser/--no-browser", help="Open LangSmith Studio in browser")] = True,
    workers:    Annotated[int,  typer.Option("--workers",         help="Max concurrent jobs per worker")] = 10,
    api_key:    Annotated[str,  typer.Option("--api-key",         help="API key override", envvar="ANTHROPIC_API_KEY")] = "",
    base_url:   Annotated[str,  typer.Option("--base-url",        help="Base URL / proxy override")] = "",
    target:     Annotated[str,  typer.Option("--target",          help="Per-target memory scope (IP, hostname, project)")] = "",
    rate_limit: Annotated[str,  typer.Option("--rate-limit",      help="Rate limit profile: aggressive | normal | stealth")] = "",
    log_level:  Annotated[str,  typer.Option("--log-level",       help="Server log level")] = "warning",
    env_file:   Annotated[Optional[str], typer.Option("--env-file", help=".env file for the server subprocess")] = None,
    hitl:       Annotated[bool, typer.Option("--hitl/--no-hitl", help="Enable HITL approval prompts for all tool calls (requires interactive UI client)")] = False,
) -> None:
    """Serve a RAI agent via the LangGraph API (no langgraph.json required).

    \b
    Loads the agent identically to the TUI: main-agent MCP tools and all
    subagent MCP tools are loaded in parallel before the graph is built.

    \b
    Examples
    --------
        rai serve                               # dev + Studio, port 2024
        rai serve --no-dev --port 8080          # plain server, no hot reload
        rai serve --agent pentest               # serve a specific agent
        rai serve --host 0.0.0.0 --workers 4    # bind all interfaces
        rai serve --target 10.0.0.1 --rate-limit aggressive

    \b
    API endpoints (once running)
    ----------------------------
        GET  http://HOST:PORT/ok              health check
        POST http://HOST:PORT/runs/stream     stream a run
        POST http://HOST:PORT/threads         create thread
        GET  http://HOST:PORT/docs            OpenAPI docs
    """
    from rai.cli.main import _bootstrap, _resolve_model
    _bootstrap()

    resolved_model = _resolve_model(model)
    src_path = str(Path(__file__).parent.parent.parent.resolve())  # …/src
    cwd = str(Path.cwd())

    mode_label = "dev (hot reload)" if dev else "server"
    typer.echo(
        f"RAI serve — agent={agent!r}  model={resolved_model!r}  "
        f"mode={mode_label}  {host}:{port}"
    )

    with tempfile.TemporaryDirectory(prefix="rai_serve_") as tmp_str:
        tmp = Path(tmp_str)
        config_path = _write_workspace(
            tmp,
            src_path=src_path,
            default_model=resolved_model,
            env_file=env_file,
        )
        env = _build_env(
            model=resolved_model,
            agent=agent,
            api_key=api_key,
            base_url=base_url,
            target=target,
            rate_limit=rate_limit,
            cwd=cwd,
            hitl=hitl,
        )

        typer.echo(f"Workspace: {tmp_str}")
        typer.echo("Press Ctrl-C to stop.\n")

        _spawn_langgraph(
            config_path,
            _ServeConfig(
                port=port,
                host=host,
                reload=dev,
                workers=workers,
                browser=browser,
                log_level=log_level,
            ),
            env,
            cwd=tmp_str,
        )
